export const docMetaMap = {
  python: {
    titleEn: 'Python',
    description: 'Python 3.14 সহ শুরু থেকে এক্সপার্ট লেভেল — syntax, OOP, async, নতুন ফিচার সব।',
    chapters: {
      'intro': { title: 'Python কী ও কেন শিখবে', subtitle: 'শুরুর কথা' },
      'syntax-basics': { title: 'Syntax আর বেসিক কনসেপ্ট' },
      'control-flow': { title: 'Control Flow — if/else, loop, function' },
      'functions': { title: 'Functions গভীরে — args, kwargs, lambda, scope', subtitle: 'Deep dive into functions' },
      'comprehensions': { title: 'Comprehensions — list, dict, set, gen' },
      'data-structures': { title: 'Data Structures — list, tuple, dict, set' },
      'strings-regex': { title: 'Strings ও Regex গভীরে' },
      'exception-handling': { title: 'Exception Handling — try/except থেকে custom error' },
      'file-io': { title: 'File I/O — read, write, pathlib, json/csv' },
      'oops': { title: 'Object Oriented Programming' },
      'magic-dataclasses': { title: 'Magic Methods, Dataclass ও Property', subtitle: 'Dunder, dataclass, @property' },
      'decorators': { title: 'Decorators গভীরে', subtitle: 'Function ও class decorator' },
      'generators-iterators': { title: 'Generators ও Iterators', subtitle: 'yield, lazy evaluation, itertools' },
      'context-managers': { title: 'Context Managers — with স্টেটমেন্ট' },
      'modules-packages': { title: 'Modules ও Packages', subtitle: 'import সিস্টেম, namespace package' },
      'venv-packaging': { title: 'Virtual Environment, pip ও Packaging', subtitle: 'venv, uv, pyproject.toml' },
      'type-hints': { title: 'Type Hints ও Static Typing', subtitle: 'typing, PEP 695, mypy, pyright' },
      'stdlib-gems': { title: 'Standard Library এর মণিকা', subtitle: 'collections, itertools, functools, pathlib' },
      'async-concurrency': { title: 'Async/Await ও Concurrency', subtitle: 'asyncio, threading, multiprocessing' },
      'testing': { title: 'Testing — pytest, fixture, mocking' },
      'best-practices': { title: 'Best Practices — Pythonic, PEP, debugging', subtitle: 'PEP 8, idioms, logging, profiling' },
      'metaclasses': { title: 'Metaclasses ও Descriptors', subtitle: 'Advanced OOP' },
      'python314-features': { title: 'Python 3.14 এর নতুন ফিচার', subtitle: 'free-threaded, JIT, template strings' },
    },
  },
  rust: {
    titleEn: 'Rust',
    description: 'Rust 1.85 — ownership, borrowing, lifetimes, async — শুরু থেকে এক্সপার্ট লেভেল, Python/C++ এর সাথে তুলনা করে সহজ ব্যাখ্যা।',
    chapters: {
      'intro': { title: 'Rust কী ও কেন শিখবে', subtitle: 'C/C++ এর উত্তরসূরি, memory safety ছাড়াই performance' },
      'syntax-basics': { title: 'Syntax আর বেসিক কনসেপ্ট', subtitle: 'variable, mut, data type, shadowing' },
      'control-flow': { title: 'Control Flow — if/else, loop, match', subtitle: 'loop, while, for, match expression' },
      'ownership': { title: 'Ownership — Rust এর হার্ট', subtitle: 'কেন GC নেই, move semantics, drop' },
      'borrowing-references': { title: 'Borrowing ও References', subtitle: '& ও &mut, borrow rules, dangling reference' },
      'lifetimes': { title: 'Lifetimes গভীরে', subtitle: "'a annotation, elision rules, static lifetime" },
      'structs-methods': { title: 'Structs ও Methods', subtitle: 'struct, tuple struct, impl block, associated functions' },
      'enums-pattern-matching': { title: 'Enums ও Pattern Matching', subtitle: 'Option, match, if let, while let, exhaustive' },
      'collections': { title: 'Collections — Vec, HashMap', subtitle: 'Vec, String, HashMap, BTreeMap' },
      'strings': { title: 'Strings গভীরে — String vs &str', subtitle: 'ownership, UTF-8, slicing, performance' },
      'error-handling': { title: 'Error Handling — Result, Option, ?', subtitle: 'panic vs Result, ? operator, custom error, thiserror' },
      'traits-generics': { title: 'Traits ও Generics', subtitle: 'trait bound, impl Trait, trait object, dyn' },
      'iterators-closures': { title: 'Iterators ও Closures', subtitle: 'map, filter, collect, Fn/FnMut/FnOnce' },
      'modules-cargo': { title: 'Modules, Crates ও Cargo', subtitle: 'mod, pub, use, Cargo.toml, workspace' },
      'smart-pointers': { title: 'Smart Pointers — Box, Rc, RefCell', subtitle: 'heap allocation, shared ownership, interior mutability' },
      'concurrency': { title: 'Concurrency ও Threads', subtitle: 'thread::spawn, Send/Sync, Mutex, channel' },
      'async-await': { title: 'Async/Await', subtitle: 'Future, tokio, async fn, select!, pin' },
      'testing': { title: 'Testing — Unit, Integration, Doc', subtitle: '#[test], #[cfg(test)], assert!, property test' },
      'macros': { title: 'Macros — Declarative ও Procedural', subtitle: 'macro_rules!, derive macro, attribute macro' },
      'best-practices': { title: 'Best Practices ও Rust Idioms', subtitle: 'clippy, idioms, error handling patterns, performance' },
    },
  },
  numpy: {
    titleEn: 'NumPy',
    description: 'NumPy array, vectorization, broadcasting — ডেটা সায়েন্সের ভিত্তি একদম A থেকে Z।',
    chapters: {
      'intro': { title: 'NumPy কী ও ইনস্টল' },
      'array-basics': { title: 'Array তৈরি আর বেসিক অপারেশন' },
      'dtypes-shape': { title: 'Dtype সিস্টেম ও Shape Manipulation', subtitle: 'reshape, transpose, astype' },
      'indexing-slicing': { title: 'Indexing আর Slicing' },
      'broadcasting': { title: 'Broadcasting আর Vectorization' },
      'ufuncs-vectorization': { title: 'Universal Functions ও Vectorize', subtitle: 'ufunc, np.where, vectorize' },
      'random': { title: 'Random Number ও Reproducibility', subtitle: 'Generator, distributions, seeding' },
      'io-save-load': { title: 'Save/Load — npy, npz, memmap' },
      'structured-masked': { title: 'Structured ও Masked Arrays', subtitle: 'Record arrays, missing data' },
      'linear-algebra': { title: 'Linear Algebra আর রিয়েল ইউজ' },
      'performance-real-world': { title: 'Performance Tips ও Real World', subtitle: 'NumPy → image, পারফরম্যান্স' },
    },
  },
  pandas: {
    titleEn: 'Pandas',
    description: 'DataFrame, Series, groupby, merge — রিয়েল ডেটা নিয়ে কাজ করার সব হাতিয়ার।',
    chapters: {
      'intro': { title: 'Pandas কী ও Series/DataFrame' },
      'load-inspect': { title: 'ডেটা লোড আর দেখা' },
      'clean-filter': { title: 'Filter, Select আর Clean করা' },
      'apply-transform': { title: 'Apply, Map ও Transform', subtitle: 'row-wise অপারেশন, lambda' },
      'groupby-merge': { title: 'GroupBy, Merge আর Pivot' },
      'time-series': { title: 'Time Series — DatetimeIndex, resample', subtitle: 'rolling, shift, timezone' },
      'multiindex-reshaping': { title: 'MultiIndex ও Reshaping', subtitle: 'stack/unstack, melt, pivot' },
      'strings-categorical': { title: 'String accessor ও Categorical', subtitle: '.str, .cat dtype' },
      'io-export': { title: 'I/O ও Export — parquet, excel, sql' },
      'real-dataset': { title: 'রিয়েল ডেটাসেট নিয়ে কাজ' },
    },
  },
  projects: {
    titleEn: 'Python + NumPy + Pandas Projects',
    description: 'বাস্তব প্রজেক্ট বানিয়ে Python, NumPy আর Pandas একসাথে ব্যবহার করা শেখা।',
    chapters: {
      'expense-tracker': { title: 'প্রজেক্ট ১: Expense Tracker' },
      'grade-calculator': { title: 'প্রজেক্ট ২: Grade Calculator' },
      'data-analysis': { title: 'প্রজেক্ট ৩: Sales Data Analysis' },
      'web-scraper': { title: 'প্রজেক্ট ৪: Web Scraper', subtitle: 'requests + pandas' },
      'api-consumer': { title: 'প্রজেক্ট ৫: API Consumer', subtitle: 'JSON API → DataFrame' },
      'capstone': { title: 'Capstone: ছোট ডেটা পাইপলাইন' },
    },
  },
  statistics: {
    titleEn: 'Statistics for AI',
    description: 'Descriptive stats, probability, hypothesis testing, Bayes — AI engineer হতে যা যা লাগে সব।',
    chapters: {
      'intro': { title: 'Statistics কী ও কেন দরকার' },
      'descriptive': { title: 'Descriptive Statistics', subtitle: 'mean, median, mode, variance, std, percentile' },
      'probability': { title: 'Probability Basics', subtitle: 'sample space, conditional, Bayes theorem' },
      'distributions': { title: 'Probability Distributions', subtitle: 'normal, binomial, Poisson, uniform' },
      'sampling-clt': { title: 'Sampling ও Central Limit Theorem', subtitle: 'sampling methods, CLT, confidence interval' },
      'hypothesis-testing': { title: 'Hypothesis Testing', subtitle: 'p-value, t-test, chi-square, A/B testing' },
      'correlation-regression': { title: 'Correlation ও Regression', subtitle: 'Pearson, Spearman, ANOVA basics' },
    },
  },
  git: {
    titleEn: 'Git, CI & CD',
    description: 'Git version control, branching, GitHub Actions CI/CD — কোড ম্যানেজ ও অটোমেট করা।',
    chapters: {
      'intro': { title: 'Git কী ও কেন দরকার' },
      'basic-workflow': { title: 'Basic Workflow — init, add, commit' },
      'branching': { title: 'Branching আর Merge' },
      'rebasing-stash': { title: 'Rebase, Stash ও Cherry-pick', subtitle: 'interactive rebase, reflog' },
      'remote-github': { title: 'Remote আর GitHub' },
      'tags-releases': { title: 'Tags ও Releases', subtitle: 'semver, changelog, GitHub release' },
      'ci-cd': { title: 'CI/CD আর GitHub Actions' },
      'best-practices': { title: 'Best Practices — commit convention, hooks', subtitle: '.gitignore deep, submodules' },
    },
  },
  linux: {
    titleEn: 'Linux Basics',
    description: 'Terminal, ফাইল সিস্টেম, permission, shell — Linux এ সাবলীল হওয়ার সব মূল বিষয়।',
    chapters: {
      'intro': { title: 'Linux ও Terminal পরিচিতি' },
      'files-permissions': { title: 'ফাইল সিস্টেম আর Permission' },
      'process-text': { title: 'Process আর Text Tools' },
      'users-groups': { title: 'Users, Groups ও sudo', subtitle: 'useradd, sudoers, ownership' },
      'networking': { title: 'Networking বেসিক', subtitle: 'ip, ping, ssh, scp, curl' },
      'package-management': { title: 'Package Management', subtitle: 'apt, dnf, snap, flatpak' },
      'shell-basics': { title: 'Shell Scripting বেসিক' },
      'systemd-services': { title: 'Systemd ও Service Management', subtitle: 'systemctl, journalctl' },
      'archive-compression': { title: 'Archive ও Compression', subtitle: 'zip, unzip, tar, gzip, 7z' },
      'download-transfer': { title: 'File Download ও Transfer', subtitle: 'wget, curl, scp, rsync' },
    },
  },
  caddy: {
    titleEn: 'Caddy Server',
    description: 'Caddy ওয়েব সার্ভার — automatic HTTPS, reverse proxy, সহজ কনফিগ সব।',
    chapters: {
      'intro': { title: 'Caddy কী ও ইনস্টল' },
      'static-reverse-proxy': { title: 'Static File আর Reverse Proxy' },
      'configuration': { title: 'Configuration — Caddyfile ও JSON', subtitle: 'admin API, environment, adapt' },
      'auto-https': { title: 'Automatic HTTPS' },
      'modules-plugins': { title: 'Modules ও Plugins', subtitle: 'extend Caddy, modules' },
      'advanced-config': { title: 'Advanced Caddyfile' },
    },
  },
  docker: {
    titleEn: 'Docker',
    description: 'Container, image, compose, volume — Docker দিয়ে অ্যাপ প্যাকেজ ও ডেপ্লয় করা।',
    chapters: {
      'intro': { title: 'Docker কী ও কেন ব্যবহার' },
      'image-container': { title: 'Image আর Container' },
      'dockerfile': { title: 'Dockerfile লেখা' },
      'networking': { title: 'Docker Networking', subtitle: 'bridge, host, custom network' },
      'compose-volume': { title: 'Docker Compose আর Volume' },
      'multistage-best-practices': { title: 'Multi-stage Build ও Best Practices', subtitle: '.dockerignore, layer caching' },
      'security-production': { title: 'Production Security', subtitle: 'non-root, scan, registry' },
    },
  },
  redis: {
    titleEn: 'Redis',
    description: 'In-memory database — caching, sessions, pub/sub, streams, rate limiting, vector search।',
    chapters: {
      'intro': { title: 'Redis কী ও Install', subtitle: 'CLI basics, data types overview' },
      'data-structures': { title: 'Data Structures গভীরে', subtitle: 'String, Hash, List, Set, Sorted Set, HyperLogLog' },
      'caching-patterns': { title: 'Caching Patterns', subtitle: 'cache-aside, write-through, stampede prevention, TTL' },
      'streams-pubsub': { title: 'Streams ও Pub/Sub', subtitle: 'consumer groups, message durability, fan-out' },
      'advanced-features': { title: 'Advanced — Lua, Rate Limit, Vector', subtitle: 'Lua scripting, rate limiter, vector search' },
      'practical': { title: 'রিয়েল ইমপ্লিমেন্টেশন', subtitle: 'Python redis-py, session store, architecture' },
    },
  },
  auth: {
    titleEn: 'JWT & OAuth 2.0',
    description: 'Token based auth, JWT স্ট্রাকচার, OAuth 2.0 flow — মডার্ন অথেন্টিকেশন।',
    chapters: {
      'auth-basics': { title: 'Authentication vs Authorization' },
      'passwords-hashing': { title: 'Password ও Hashing', subtitle: 'bcrypt, argon2, salt, timing' },
      'sessions-cookies': { title: 'Session ও Cookie Management', subtitle: 'secure cookie, CSRF, SameSite' },
      'jwt-deep-dive': { title: 'JWT একদম গভীরে' },
      'oauth-flows': { title: 'OAuth 2.0 Flow' },
      'practical': { title: 'রিয়েল ইমপ্লিমেন্টেশন' },
    },
  },
  ml: {
    titleEn: 'Machine Learning',
    description: 'Supervised, unsupervised, model training, evaluation — ML এর পুরো জগত।',
    chapters: {
      'intro': { title: 'Machine Learning কী' },
      'math-foundations': { title: 'Math Foundations', subtitle: 'linear algebra, probability, calculus for ML' },
      'data-prep': { title: 'Data Prep ও Feature Engineering', subtitle: 'scaling, encoding, train/test split' },
      'supervised': { title: 'Supervised — Regression আর Classification' },
      'cost-optimization': { title: 'Cost Function ও Gradient Descent', subtitle: 'MSE, cross-entropy, SGD, learning rate' },
      'linear-models-deep': { title: 'Linear Models গভীরে', subtitle: 'OLS, logistic regression, L1/L2 regularization' },
      'bias-variance': { title: 'Bias-Variance Tradeoff', subtitle: 'overfitting, underfitting, learning curves' },
      'unsupervised': { title: 'Unsupervised আর Clustering' },
      'model-tuning': { title: 'Model Tuning ও Hyperparameter', subtitle: 'grid search, cross-validation' },
      'evaluation': { title: 'Model Evaluation' },
      'ensemble': { title: 'Ensemble Methods', subtitle: 'bagging, boosting, XGBoost' },
      'real-project': { title: 'রিয়েল প্রজেক্ট: Iris' },
    },
  },
  nlp: {
    titleEn: 'Natural Language Processing',
    description: 'Text processing, tokenization, transformers — ভাষা নিয়ে কম্পিউটারের কাজ।',
    chapters: {
      'intro': { title: 'NLP কী ও কোথায় ব্যবহার' },
      'preprocessing': { title: 'Text Preprocessing আর Tokenization' },
      'word-embeddings': { title: 'Word Embeddings', subtitle: 'word2vec, GloVe, dense vectors' },
      'classical-nlp': { title: 'Classic NLP — Sentiment আর Classification' },
      'transformers': { title: 'Transformers আর LLM' },
      'llm-practical': { title: 'LLM প্র্যাকটিক্যাল', subtitle: 'prompting, fine-tuning, RAG, Hugging Face' },
    },
  },
  dl: {
    titleEn: 'Deep Learning',
    description: 'Neural network, CNN, RNN, PyTorch/TensorFlow — ডিপ লার্নিং একদম গভীরে।',
    chapters: {
      'intro': { title: 'Deep Learning কী' },
      'math-foundations': { title: 'Math Foundations', subtitle: 'tensor, gradient, chain rule' },
      'neural-net': { title: 'Neural Network এর কাজ' },
      'regularization-optimization': { title: 'Regularization ও Optimization', subtitle: 'dropout, batch norm, Adam, lr schedule' },
      'cnn-rnn': { title: 'CNN আর RNN' },
      'modern-architectures': { title: 'Modern Architectures', subtitle: 'attention, transformer, ViT' },
      'frameworks': { title: 'PyTorch আর TensorFlow' },
    },
  },
  cv: {
    titleEn: 'Computer Vision',
    description: 'Image processing, CNN, YOLO, SAM, transfer learning — CV এর পুরো জগত 2026 অনুযায়ী।',
    chapters: {
      'intro': { title: 'Computer Vision কী', subtitle: 'digital image, pixels, color spaces' },
      'image-processing': { title: 'Image Processing — OpenCV', subtitle: 'filtering, edge detection, morphology, threshold' },
      'cnn-architecture': { title: 'CNN Architecture গভীরে', subtitle: 'conv, pool, fc, building CNN from scratch' },
      'object-detection': { title: 'Object Detection', subtitle: 'YOLO v11, RT-DETR, NMS, mAP' },
      'segmentation': { title: 'Segmentation', subtitle: 'semantic, instance, SAM 3, U-Net' },
      'transfer-learning': { title: 'Transfer Learning', subtitle: 'pretrained, fine-tuning, ResNet, ViT, CLIP' },
      'practical': { title: 'রিয়েল প্রজেক্ট: Image Classifier', subtitle: 'custom dataset, train, evaluate, deploy' },
    },
  },
  dsa: {
    titleEn: 'DSA & Algorithms',
    description: 'Array থেকে Dynamic Programming পর্যন্ত — প্রতিটা টপিক visualization, code, আর LeetCode/Codeforces practice problems সহ।',
    chapters: {
      'intro': { title: 'C++ CP Setup & Complexity Analysis', subtitle: 'Fast I/O, Time/Space Complexity (Big O), Integer Overflow & Traps' },
      'math-number-theory': { title: 'Math & Number Theory', subtitle: 'Basic Math, GCD/LCM (Key of Multiples), Sieve of Eratosthenes, Modulo Arithmetic' },
      'arrays-strings': { title: 'Arrays, Strings & Prefix Sums', subtitle: 'Character Frequency, Palindromes, 1D & 2D Prefix Sums, Difference Array' },
      'sorting-greedy': { title: 'Sorting Algorithms & Greedy Strategy', subtitle: 'Custom Comparators, Selling Hot Pizzas, Minimize Difference, Segment Sorting' },
      'binary-search': { title: 'Binary Search & BS on Answer', subtitle: 'Classical BS, Lower/Upper Bound, Harbor Master (Ship Capacity), AC Installation Plan' },
      'two-pointers-sliding-window': { title: 'Two Pointers & Sliding Window', subtitle: 'Two Pointers, Mystic Box of Glucose (Candies Simulation), Fixed/Variable Window' },
      'trees-lca': { title: 'Trees, Tree DFS & LCA / Binary Lifting', subtitle: 'Tree Traversals, Easy Path, LCA & Binary Lifting (Pokémon Path Quest)' },
      'graphs-grid': { title: 'Graphs & 2D Grid Traversal', subtitle: 'Direction Arrays (dx/dy), 2D Grid BFS Shortest Path, Flood Fill' },
      'shortest-paths': { title: 'Shortest Path Algorithms', subtitle: 'Dijkstra Algorithm, 2-Way Dijkstra (The Delivery Milestone), State/Modulo Dijkstra' },
      'dynamic-programming': { title: 'Dynamic Programming', subtitle: '0-1 Knapsack (Dumpling Dilemma), Path Score (Grid DP), Limited Turns (Turns DP)' },
      'advanced-ds': { title: 'Advanced Data Structures', subtitle: 'Fenwick Tree / BIT (Balanced Ninja Teams), DSU (Union-Find), Segment Tree' },
    },
  },
  transformers: {
    titleEn: 'Transformers — Attention to LLMs',
    description: 'Attention Is All You Need থেকে GPT-4 পর্যন্ত — সম্পূর্ণ Transformer architecture, 3Blue1Brown স্টাইলে গভীরভাবে।',
    chapters: {
      'intro': { title: 'Transformer কী ও কেন বিপ্লব', subtitle: '2017 paper, RNN limitations, parallel processing' },
      'seq2seq-evolution': { title: 'Pre-Transformer: Seq2Seq ও RNN', subtitle: 'encoder-decoder, bottleneck problem, Bahdanau attention' },
      'attention-intuition': { title: 'Attention এর ইনটুইশন', subtitle: 'Q/K/V, contextual embeddings, library analogy' },
      'self-attention': { title: 'Self-Attention গণিত ও Multi-Head', subtitle: 'softmax(QK^T/√d_k)V, scaled dot-product, multi-head' },
      'positional-encoding': { title: 'Positional Encoding', subtitle: 'sinusoidal, learned, RoPE, ALiBi' },
      'architecture': { title: 'Complete Transformer Architecture', subtitle: 'encoder, decoder, cross-attention, FFN, residual+norm' },
      'training': { title: 'Training Transformers', subtitle: 'teacher forcing, cross-entropy, warmup, dropout, label smoothing' },
      'bert': { title: 'BERT ও Encoder-only Models', subtitle: 'MLM, NSP, fine-tuning, RoBERTa, DeBERTa' },
      'gpt': { title: 'GPT ও Decoder-only Models', subtitle: 'autoregressive, causal mask, scaling laws, GPT-1 to GPT-4' },
      'modern-improvements': { title: 'Modern Improvements', subtitle: 'RoPE, Flash Attention, KV Cache, GQA, MoE' },
      'vision-transformer': { title: 'Vision Transformer (ViT)', subtitle: 'patch embedding, ViT vs CNN, DeiT, Swin, CLIP' },
      'practical': { title: 'Practical — HuggingFace ও Fine-tuning', subtitle: 'BPE, pipeline, LoRA, QLoRA, RAG, quantization' },
      'embeddings-deep': { title: 'Embeddings Deep Dive — Static থেকে Contextual', subtitle: 'word2vec → ELMo → BERT: কীভাবে meaning context-aware হয়' },
      'positional-encoding-deep': { title: 'Positional Encoding Deep Dive — Sin/Cos গণিত', subtitle: 'why sin/cos, frequency formula, dimension analysis, geometric intuition' },
      'layer-representations': { title: 'Layer Representations — প্রতিটা Layer কী শেখে', subtitle: 'probing tasks, layer-wise analysis, what each layer learns' },
    },
  },
  english: {
    titleEn: 'English for Developers',
    description: 'বাংলায় English শেখার সবচেয়ে practical গাইড — grammar, tech vocabulary, docs পড়া, error message বোঝা, professional লেখা।',
    chapters: {
      'intro': { title: 'Developer হিসেবে English কেন দরকার', subtitle: 'কেন শিখবে, কীভাবে শিখবে, roadmap' },
      'basic-grammar': { title: 'Basic Grammar — Sentence Structure', subtitle: 'Subject-Verb-Object, parts of speech, word order' },
      'tenses': { title: 'Tense — Past, Present, Future', subtitle: 'code-এ কোন tense লাগে, common patterns' },
      'articles-prepositions': { title: 'Articles (a/an/the) ও Prepositions', subtitle: 'in/on/at/of/for — developer writing-এ বারবার আসে' },
      'tech-vocabulary': { title: 'Tech Vocabulary — 100+ Words', subtitle: 'deploy, refactor, debug, deprecated — সব প্রতিদিনের word' },
      'common-phrases': { title: 'Common Tech Phrases', subtitle: 'throws, returns, is deprecated, optional parameter' },
      'reading-docs': { title: 'Documentation পড়ার Technique', subtitle: 'API docs, README, MDN, Python docs কীভাবে পড়বে' },
      'error-messages': { title: 'Error Message বোঝা ও Fix করা', subtitle: 'Traceback, stack trace, common error patterns' },
      'writing-commits': { title: 'Git Commit ও PR Description লেখা', subtitle: 'conventional commits, PR body, review comments' },
      'code-comments': { title: 'Code Comment ও Documentation লেখা', subtitle: 'docstring, inline comment, README writing' },
      'email-communication': { title: 'Professional Email ও Communication', subtitle: 'team email, standup update, asking for help' },
      'reading-practice': { title: 'Reading Practice — Tech Articles', subtitle: 'short tech passages with vocabulary help' },
      'daily-conversation': { title: 'Daily Conversation — প্রতিদিনের কথা', subtitle: '100+ daily sentences: কি করছো, কোথায় যাচ্ছো, খাবে কিনা' },
      'phrasal-verbs': { title: 'Phrasal Verbs — 50+ টা দরকারি', subtitle: 'get up, look forward to, give up — meaning ও example সহ' },
      'common-idioms': { title: 'Common Idioms — প্রতিদিনের Idioms', subtitle: 'piece of cake, under the weather, on the same page' },
    },
  },
  fastapi: {
    titleEn: 'FastAPI — Modern Python Web Framework',
    description: 'FastAPI 0.136 — Python এর সবচেয়ে দ্রুত web framework। Pydantic v2, async, auto-docs, deployment — A to Z 2026।',
    chapters: {
      'intro': { title: 'FastAPI কী ও কেন শিখবে', subtitle: 'ASGI vs WSGI, Starlette, Pydantic, performance' },
      'setup-first-app': { title: 'Setup ও First App', subtitle: 'install, uvicorn, first endpoint, auto Swagger docs' },
      'path-query-params': { title: 'Path, Query ও Request Body', subtitle: 'path params, query params, validation, Pydantic models' },
      'pydantic-deep': { title: 'Pydantic v2 গভীরে', subtitle: 'model validators, field validators, computed fields, serialization' },
      'dependency-injection': { title: 'Dependency Injection — Depends()', subtitle: 'reusable logic, caching, overrides for testing' },
      'middleware-cors': { title: 'Middleware ও CORS', subtitle: 'CORS, GZip, custom middleware, rate limiting' },
      'authentication-security': { title: 'Authentication ও Security', subtitle: 'JWT, OAuth2PasswordBearer, password hashing, scopes' },
      'database-sqlmodel': { title: 'Database — SQLModel ও SQLAlchemy', subtitle: 'async SQLAlchemy, SQLModel, CRUD, Alembic migration' },
      'background-tasks': { title: 'Background Tasks ও Webhooks', subtitle: 'BackgroundTasks, async jobs, webhooks, task queues' },
      'testing-deployment': { title: 'Testing ও Production Deployment', subtitle: 'pytest + httpx, Docker, Gunicorn + Uvicorn, CI/CD' },
    },
  },
  websocket: {
    titleEn: 'WebSocket — Real-Time Communication',
    description: 'WebSocket protocol থেকে production chat app — FastAPI WebSocket, connection management, Redis scaling, সব 2026 patterns।',
    chapters: {
      'intro': { title: 'WebSocket কী ও কেন দরকার', subtitle: 'HTTP vs WebSocket, use cases, real-time apps' },
      'protocol-deep': { title: 'WebSocket Protocol গভীরে', subtitle: 'handshake, frames, ping/pong, close codes, subprotocols' },
      'fastapi-websocket': { title: 'FastAPI তে WebSocket', subtitle: 'WebSocket endpoint, accept, send/receive, JSON messages' },
      'connection-manager': { title: 'Connection Manager ও Broadcasting', subtitle: 'active connections, broadcast, rooms, typing indicators' },
      'authentication': { title: 'WebSocket Authentication', subtitle: 'token in query param, origin checking, connection validation' },
      'scaling-redis': { title: 'Scaling — Redis Pub/Sub', subtitle: 'multi-worker, Redis pub/sub, presence detection, fan-out' },
      'production': { title: 'Production Deployment', subtitle: 'Nginx, sticky sessions, monitoring, reconnection, heartbeats' },
    },
  },
  sqlalchemy: {
    titleEn: 'SQLAlchemy 2.0 & Alembic',
    description: 'SQLAlchemy 2.0+ ORM, Mapped/mapped_column, AsyncSession, Alembic migration, relationships & production query optimization — A to Z 2026।',
    chapters: {
      'intro': { title: 'SQLAlchemy কী ও 2.0 Paradigm', subtitle: 'Core vs ORM, 1.4 vs 2.0 style, DeclarativeBase' },
      'engine-connection': { title: 'Engine, Connection & Connection Pooling', subtitle: 'create_engine, pooling, transaction management' },
      'declarative-models': { title: 'Declarative Models — Mapped & mapped_column', subtitle: 'Mapped[T], mapped_column, Base class, type safety' },
      'crud-operations': { title: 'CRUD Operations & Modern Select', subtitle: 'Session, select(), insert(), update(), delete()' },
      'relationships': { title: 'Relationships & Joins', subtitle: 'relationship, ForeignKey, one-to-many, many-to-many' },
      'loading-strategies': { title: 'Loading Strategies — Lazy, Joined, Selectin', subtitle: 'joinedload, selectinload, write-only collections, N+1 fix' },
      'asyncio': { title: 'Async SQLAlchemy — AsyncEngine & AsyncSession', subtitle: 'create_async_engine, asyncpg, aiosqlite, AsyncSession' },
      'alembic-migrations': { title: 'Database Migrations with Alembic', subtitle: 'alembic init, revision --autogenerate, upgrade head' },
      'advanced-features': { title: 'Advanced Querying & Hybrid Attributes', subtitle: 'hybrid_property, CTE, window functions, raw text()' },
      'production-best-practices': { title: 'Production Best Practices & Performance', subtitle: 'session lifecycle, pooling tuning, batch operations' },
    },
  },
  pytorch: {
    titleEn: 'PyTorch 2.x — Deep Learning',
    description: 'PyTorch 2.6/2.7 — Tensors, Autograd, nn.Module, DataLoaders, Training Loop, GPU/CUDA/MPS, torch.compile & FlexAttention — A to Z 2026।',
    chapters: {
      'intro': { title: 'PyTorch কী ও কেন ডিপ লার্নিং এর সেরা choice', subtitle: 'Eager execution, PyTorch 2.x revolution, ecosystem' },
      'tensors': { title: 'PyTorch Tensors A to Z', subtitle: 'Creation, dtypes, shapes, indexing, broadcasting, NumPy integration' },
      'autograd': { title: 'Autograd Engine — Automatic Differentiation', subtitle: 'requires_grad, backward(), grad, computational graph' },
      'nn-module': { title: 'Building Neural Networks with nn.Module', subtitle: 'nn.Module, forward(), Linear, Conv2d, Sequential' },
      'data-loading': { title: 'Dataset & DataLoader Pipeline', subtitle: 'Custom Dataset, DataLoader, batching, workers, transforms' },
      'training-loop': { title: 'Training Loop — Loss, Optimizer & Scheduler', subtitle: 'Loss functions, SGD/AdamW, zero_grad(), step(), LR scheduler' },
      'gpu-hardware': { title: 'GPU & Hardware Acceleration (CUDA/MPS/ROCm)', subtitle: 'torch.device, CUDA, Apple Silicon MPS, Mixed Precision (AMP)' },
      'torch-compile': { title: 'PyTorch 2.x torch.compile & TorchInductor', subtitle: 'torch.compile, Triton backend, FlexAttention, speedups' },
      'saving-loading': { title: 'Saving & Loading Models', subtitle: 'state_dict, torch.save, torch.load, weights_only, checkpoints' },
      'transfer-learning-finetune': { title: 'Transfer Learning & Model Fine-tuning', subtitle: 'Pretrained models, torchvision, PEFT, LoRA, LLM fine-tuning' },
    },
  },
};

export function getDocMeta(path) {
  const parts = path.split('/').filter(Boolean);
  if (parts[0] !== 'docs') return null;

  if (parts.length === 1) {
    return {
      title: 'Docs — A to Z গাইড | BookmarkVault',
      description: 'Python, DSA, Rust, NumPy, Pandas, FastAPI, Docker, PyTorch, Linux, ML, Deep Learning... সম্পূর্ণ বাংলায় কোড সহ A to Z গাইড।',
    };
  }

  const categoryId = parts[1];
  const category = docMetaMap[categoryId];
  if (!category) return null;

  if (parts.length === 2) {
    return {
      title: `${category.titleEn} — Docs | BookmarkVault`,
      description: category.description,
    };
  }

  const chapterId = parts[2];
  const chapter = category.chapters?.[chapterId];
  if (chapter) {
    const subtitleStr = chapter.subtitle ? `${chapter.subtitle} — ` : '';
    return {
      title: `${chapter.title} — ${category.titleEn} Docs | BookmarkVault`,
      description: `${subtitleStr}${category.description}`,
    };
  }

  return {
    title: `${category.titleEn} — Docs | BookmarkVault`,
    description: category.description,
  };
}
