name: Build and Release Android APK

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install NPM Packages
        run: npm ci || npm install

      - name: Build Web App
        run: npm run build

      - name: Sync Capacitor
        run: npx cap sync android

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x android/gradlew

      - name: Build with Gradle
        run: cd android && ./gradlew assembleDebug

      - name: Rename APK
        run: mv android/app/build/outputs/apk/debug/app-debug.apk Bookmark-${{ github.ref_name }}.apk

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: Bookmark-${{ github.ref_name }}.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
